blank_issues_enabled: false
contact_links:
  - name: ❓ Simple question - Discord chat
    url: https://discord.com/invite/flarenetwork
    about: This issue tracker is not for technical support. Please use the Discord chat, and ask the community for help.
