name: Documentation
description: Report an issue related to documentation
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for issues with documentation, including:

        - Documenting undocumented APIs;
        - Updating external links;

        You can proceed directly to sending a pull request without filing this issue, and we can improve on your work.
        If you think some of the requirements above are not met, or if you are not able to contribute yourself, the issue is still welcomed.

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the issue is.
    validations:
      required: true
