name: Feature Request
description: Submit a feature request for the documentation
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        This template is strictly used for feature requests, including:

        - Requesting a new guide or tutorial;
        - Requesting elaboration on a particular topic;

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
    validations:
      required: true
