name: Request a new Feed
description: Make a request for adding a new feed to FTSOv2
title: "[req]: "
labels: "feed request"
body:
  - type: input
    attributes:
      label: Feed Name
      description: "The name of the feed"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Justification
      description: "A clear and concise explanation of why you are requesting this feed."
    validations:
      required: true
  - type: textarea
    attributes:
      label: CeXs
      description: "List out all CeXs/aggregators on which this feed is traded."
    validations:
      required: true
